apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-lab-1-deployment
spec:
  replicas: 3  # Specifies the number of instances you want running
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ac-lab-1
  template:
    metadata:
      labels:
        app: ac-lab-1
    spec:
      containers:
      - name: ac-lab-1
        image: acrworkflow1713257063064.azurecr.io/image-workflow-1713257063064:latest
        ports:
        - containerPort: 8080  # Adjust the port if your app uses a different one
      livenessProbe:
        httpGet:
          path: /health-check
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
