name: Azure Login and Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deployment version to rollback to'
        required: true

env:
    ACR_RESOURCE_GROUP: ac-labs
    AZURE_CONTAINER_REGISTRY: acrworkflow1713257063064
    CLUSTER_NAME: ac-labs-kluster
    CLUSTER_RESOURCE_GROUP: ac-labs
    CONTAINER_NAME: image-workflow-1713257063064

jobs:
  deploy:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure login
      uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Connect to AKS
      run: |
        az aks get-credentials --resource-group ${{env.ACR_RESOURCE_GROUP}} --name ${{env.CLUSTER_NAME}} --overwrite-existing

    - name: Rollback to previous deployment version
      run: kubectl rollout undo deployment/ac-lab-1-deployment
